---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-mac
  namespace: default
spec:
  targetNamespace: default
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: default
    namespace: flux-system
  path: ./apps/base
  prune: true
  validation: client
  patchesStrategicMerge:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: metrics-server
      spec:
        values:
          commonLabels:
            environment: mac
