---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: webhook
  namepsace: flux-system
spec:
  type: generic
  address: https://webhook.site/054f90e7-3d84-47e1-9b7e-651217d3760a 
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: all
  namespace: flux-system
spec:
  providerRef:
    name: webhook
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: '*'
      namespace: '*'
