apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: hello-http
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/vlj91/hello-http
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: hello-http
  namespace: flux-system
spec:
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: hello-http
  path: ./deploy/base
  prune: false
  interval: 1m
