apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: hello-http
  namespace: default
spec:
  interval: 1m
  url: https://github.com/vlj91/hello-http
  ref:
    branch: master