---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: hello-http
  namespace: default
spec:
  interval: 1m
  url: https://github.com/vlj91/hello-http
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: hello-http
  namespace: default
spec:
  targetNamespace: default
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: hello-http
    namespace: default
  path: ./deploy/base
  prune: true
  validation: client
