---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 1m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metrics-server
      version: "6.0.4"
      interval: 1m
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
